#!/bin/zsh

. "$HOME/.zsh/functions/paths"

# should probably run in .zprofile, but if not...
if [[ -z "$HOMEBREW_PREFIX" ]]; then
    if [[ -x "/opt/homebrew/bin/brew" ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
fi

__prepend_paths "/opt/homebrew/bin"

if [[ -d "/opt/homebrew/opt/util-linux/bin" ]]; then
    __prepend_path "/opt/homebrew/opt/util-linux/bin"
fi

# if hash brew 2>/dev/null; then
#     export HOMEBREW_GITHUB_API_TOKEN=$(ghost get --name HOMEBREW_GITHUB_API_TOKEN --show-password -o password)
# fi
