#!/bin/zsh

# HT: https://github.com/sykora/etc/raw/master/zsh/functions/spectrum/
# Started with work by P.C. Shyamshankar <sykora@lucentbeing.com>

typeset -Ag FX FG BG

FX=(
    reset       "[00m"
    bold        "[01m"  no-bold         "[22m"
    italic      "[03m"  no-italic       "[23m"
    underline   "[04m"  no-underline    "[24m"
    blink       "[05m"  no-blink        "[25m"
    reverse     "[07m"  no-reverse      "[27m"
);

for color in {0..255}; do
    FG[$color]="[38;5;${color}m"
    BG[$color]="[48;5;${color}m"
done

# Also define 0-padded versions
for color in {000..099}; do
    FG[$color]="[38;5;${color}m"
    BG[$color]="[48;5;${color}m"
done

function xyz_index() {
    echo $((16 + ($1 * 36) + ($2 * 6) + $3))
}

function rgb_fg() {
    echo "\x1b[38;2;$1;$2;${3}m";
}
